#!/bin/bash
set -eux # -x for verbose logging to juju debug-log

HOME=`dirname $0`
. ${HOME}/common.sh

juju-log "Installing required Packages via apt-get - java"
# was giving errors trying to install jre without update first.
apt-get update
apt-get -y install openjdk-7-jre-headless curl redis-server
# set redis listener
sed -i.bak -e "s/bind 127.0.0.1/#bind ${HOST}/" /etc/redis/redis.conf
juju-log "Install upstart init script"
install -o root -g root -m 0644 ${HOME}/../files/charm/logstash-indexer.conf /etc/init/logstash-indexer.conf
sed -i "s|BASEPATH|${BASEPATH}|g" /etc/init/logstash-indexer.conf
juju-log "create logstash user"
[ -z "$(id ${USER})"] && useradd ${USER}
juju-log "install logstash and create config files"


# Check if a local copy of the jar exists
# if [ -f ${HOME}/../files/charm/logstash-${VERSION}-flatjar.jar ]
# then
#   install -o root -g root -m 0644 ${HOME}/../files/charm/logstash-${VERSION}-flatjar.jar ${BASEPATH}/bin/logstash.jar
# else
#   # Download logstash monolithic jar and checksum
#   wget -q -O ${BASEPATH}/bin/logstash.jar ${BASEURL}/logstash-${VERSION}-flatjar.jar
#   if [[ $(md5sum "${BASEPATH}/bin/logstash.jar" | cut -d " " -f 1) != ${CHECKSUM} ]]; then
#     juju-log --log-level CRITICAL "Checksum of ${BASEPATH}/bin/logstash.jar failed"
#     exit 1
#   fi
# fi

LOGSTASH_ARCHIVE_NAME=logstash-${VERSION}.tar.gz
LOCAL_LOGSTASH_ARCHIVE=${HOME}/../files/charm/${LOGSTASH_ARCHIVE_NAME}
TARGET_LOGSTASH_ARCHIVE=${WORKDIR}/${LOGSTASH_ARCHIVE_NAME}

if [ -f ${LOCAL_LOGSTASH_ARCHIVE} ]
then
  sudo install -o root -g root -m 0644 ${LOCAL_LOGSTASH_ARCHIVE} ${TARGET_LOGSTASH_ARCHIVE}
else
  # Download logstash monolithic jar and checksum
  wget -q -O ${TARGET_LOGSTASH_ARCHIVE} ${BASEURL}/${LOGSTASH_ARCHIVE_NAME}
  # if [[ $(md5sum "${BASEPATH}/bin/logstash.jar" | cut -d " " -f 1) != ${CHECKSUM} ]]; then
  #   juju-log --log-level CRITICAL "Checksum of ${BASEPATH}/bin/logstash.jar failed"
  #   exit 1
  # fi
fi

tar -xzf ${TARGET_LOGSTASH_ARCHIVE} -C ${WORKDIR}
ln -s ${WORKDIR}/logstash-${VERSION} ${BASEPATH}

juju-log "create skeleton dir"
mkdir -p ${BASEPATH}/bin
mkdir -p ${BASEPATH}/conf.d
mkdir -p ${BASEPATH}/data

echo "input {  file {     type => 'syslog'    path => ['/var/log/syslog','/var/log/kern.log','/var/log/auth.log','/var/log/dpkg.log'] sincedb_path => '${BASEPATH}' } }" > ${BASEPATH}/conf.d/input-file-syslog.conf
echo 'input { redis { host => "127.0.0.1" data_type => "list" type => "redis" tags => ["redis"] key => "logstash" message_format => "json_event" } } ' > ${BASEPATH}/conf.d/input-redis.conf
echo 'output {  elasticsearch {    embedded => true  } }' > ${BASEPATH}/conf.d/output-elasticsearch.conf

install -o root -g root -m 0644 ${HOME}/../files/charm/50-filters.conf ${BASEPATH}/conf.d/50-filters.conf

juju-log "create log file and pwn it"
touch /var/log/logstash-indexer.log
chown ${USER}. /var/log/logstash-indexer.log
juju-log "Make sure ${USER} user owns the whole kit and kaboodle"
chown -R ${USER}. ${BASEPATH}
